---
name: Build Main Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Generate image info
        id: image-info
        shell: bash
        run: |
          sha=$(echo ${{ github.sha }} | cut -c 1-7)
          echo "COMMIT_SHA=${sha}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Check if image exists in GHCR
        id: check-image
        shell: bash
        run: |
          IMAGE_TAG="ghcr.io/${{ github.repository }}:${{ env.COMMIT_SHA }}"
          echo "Checking for image: $IMAGE_TAG"
          if docker manifest inspect $IMAGE_TAG > /dev/null 2>&1; then
            echo "IMAGE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "IMAGE_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        if: ${{ env.IMAGE_EXISTS == 'false' }}
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and Push to GHCR
        if: ${{ env.IMAGE_EXISTS == 'false' }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.COMMIT_SHA }}
